config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}, path_prefix: "devise"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root "home#index"
  resources :like, only: %i[create destroy]
  resources :users, only: %i[index]
  resources :home, only: %i[index]
  
  namespace :dashboard do
    resources :sketches, only: %i[index show]
    resources :tutorials, only: %i[index show]
  end
  
  resources :dashboard, only: %i[index show]

  resources :posts do
    resources :comments, only: %i[create destroy]
  end

  resources :subscribers, only: %i[index]

  resources :plans, only: %i[index]

  namespace :plans do
    get "patron"
    get "benefactor"
  end

  namespace :payments do
    post "card"
  end
end

app/controllers/dashboard/sketches_controller.rb
class Dashboard::SketchesController < ApplicationController
    before_action :check_plan
    before_action :confirm_role

    def index
        @posts = Post.where(scope: "patron")
        @liked_posts = current_user.liked_posts
        @like = Like.new
        @total_likes = Like.all.count
        @total_fans = User.where.not(role: "admin").count
        @total_posts = @posts.count
        @creator = User.find_by(role: "admin")
    end
    
    def show
        @like = Like.new
        @post = Post.find(params[:id])
        @creator = User.find_by(role: "admin")
    end

    private

    def check_plan
        redirect_to dashboard_index_path, alert: "Upgrade your plan to access this content" unless current_user.patron? || current_user.benefactor?
    end

    def confirm_role
        redirect_to posts_path if current_user.admin?
    end
end

app/controllers/dashboard/tutorials_controller.rb
class Dashboard::TutorialsController < ApplicationController
    before_action :check_plan
    before_action :confirm_role

    def index
        @posts = Post.where(scope: "benefactor")
        @liked_posts = current_user.liked_posts
        @like = Like.new
        @total_likes = Like.all.count
        @total_fans = User.where.not(role: "admin").count
        @total_posts = @posts.count
        @creator = User.find_by(role: "admin")
    end
    
    def show
        @like = Like.new
        @post = Post.find(params[:id])
        @creator = User.find_by(role: "admin")
    end

    private

    def check_plan
        redirect_to dashboard_index_path, alert: "Upgrade your plan to access this content" unless current_user.plan == "benefactor"
    end

    def confirm_role
        redirect_to posts_path if current_user.admin?
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!
    before_action :confirm_role
    before_action :check_expiry

    def index
        @supporter_posts = Post.where(scope: "supporter")
        @patron_posts = Post.where.not(scope: "benefactor")
        @posts = Post.all
        @liked_posts = current_user.liked_posts
        @like = Like.new
        @total_likes = Like.all.count
        @total_fans = User.where.not(role: "admin").count
        @total_posts = @posts.count
        @creator = User.find_by(role: "admin")
    end

    def show
        @post = Post.find(params[:id])
        @like = Like.new
        @creator = User.find_by(role: "admin")
    end 

    private

    def confirm_role
        redirect_to posts_path if current_user.admin?
    end

    def check_expiry
        if !current_user.plan_expiration.nil? && !current_user.plan_expiration.future?
            flash[:alert] = "Your #{current_user.plan} plan has expired"
            current_user.update(plan: "supporter", plan_expiration: nil)
        end
    end

end

app/views/dashboard/_posts.html.erb
<% scope.reverse.each do |post| %>
  <div class="post">
    <div class="top">
      <div class="left">
        <%= image_tag @creator.avatar_image.attached? ? @creator.avatar_image : "profile.jpg" %>
        <div class="details">
          <div class="name">
            <%= @creator.first_name %> <%= @creator.last_name %>
          </div>
          <div class="username">
            @<%= @creator.username %>
          </div>
        </div>
        <div class="right">
          <div class="date">
          </div>
        </div>
      </div>
    </div>
    <div class="middle">
      <%= link_to dashboard_path(post.id) do %>
        <% if post.content_image.content_type.include?("image")%>
          <%= image_tag url_for(post.content_image) %>
        <% else %>
          <%= video_tag url_for(post.content_image), controls: true, height: "500px", width: "500px"%>
        <% end %>
      <% end %>
    </div>
    <div class="bottom">
      <div class="details-wrapper">
        <div class="buttons">
          <div class="left-button">
            <div class="like">
              <div class="like-button">
                <% if post.liked?(current_user) %>
                  <%= link_to post.likes.find_by(user_id: current_user.id), method: :delete, class: "unlike-post-button" do %>
                    <%= image_tag "like.png" %>
                  <% end %>
                <% else %>
                  <%= render 'layouts/like', like: @like, user_id: current_user.id, post_id: post.id %>
                <% end %>
              </div>
              <div class="count-like"></div>
            </div>
            <%= image_tag "comment.png" %>
            <%= image_tag "send.png" %>
          </div>
          <div class="right-button">
            <%= image_tag "save.png" %>
          </div>
        </div>
        <div class="down">
          <% if post.users_liked.blank? %>
          <% else %>
            <div class="liked-by">
              Liked by <span><%= pluralize(post.users_liked.count, "fan") %></span>
            </div>
          <% end %>
        </div>
        <div class="post-details">
          <span><%= post.title %></span> <%= post.description %>
        </div>
        <div class="date">
          <%= distance_of_time_in_words(DateTime.now, post.created_at) %> ago 
        </div>
      </div>
      <%= link_to dashboard_path(post.id), class: "comment" do %>
        <% if current_user.image.blank? && !current_user.avatar_image.attached? %>
          <%= image_tag "image.png" %>
        <% elsif current_user.avatar_image.attached?  %>
          <%= image_tag current_user.avatar_image %>
        <% else %>
          <%= image_tag current_user.image %>
        <% end %>
        <div class="add-comment">
          Add a comment...
        </div>
        <div class="post-button">
          Post
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/dashboard/_sketches_posts.html.erb
<% @posts.reverse.each do |post| %>
  <div class="post">
    <div class="top">
      <div class="left">
        <%= image_tag @creator.avatar_image.attached? ? @creator.avatar_image : "profile.jpg" %>
        <div class="details">
          <div class="name">
            <%= @creator.first_name %> <%= @creator.last_name %>
          </div>
          <div class="username">
            @<%= @creator.username %>
          </div>
        </div>
        <div class="right">
          <div class="date">
          </div>
        </div>
      </div>
    </div>
    <div class="middle">
      <%= link_to dashboard_sketch_path(post.id) do %>
        <% if post.content_image.content_type.include?("image")%>
          <%= image_tag url_for(post.content_image) %>
        <% else %>
          <%= video_tag url_for(post.content_image), controls: true, height: "500px", width: "500px"%>
        <% end %>
      <% end %>
    </div>
    <div class="bottom">
      <div class="details-wrapper">
        <div class="buttons">
          <div class="left-button">
            <div class="like">
              <div class="like-button">
                <% if post.liked?(current_user) %>
                  <%= link_to post.likes.find_by(user_id: current_user.id), method: :delete do %>
                    <%= image_tag "like.png" %>
                  <% end %>
                <% else %>
                  <%= render 'layouts/like', like: @like, user_id: current_user.id, post_id: post.id %>
                <% end %>
              </div>
              <div class="count-like"></div>
            </div>
            <%= image_tag "comment.png" %>
            <%= image_tag "send.png" %>
          </div>
          <div class="right-button">
            <%= image_tag "save.png" %>
          </div>
        </div>
        <div class="down">
          <% if post.users_liked.blank? %>
          <% else %>
            <div class="liked-by">
              Liked by <span><%= pluralize(post.users_liked.count, "fan") %></span>
            </div>
          <% end %>
        </div>
        <div class="post-details">
          <span><%= post.title %></span> <%= post.description %>
        </div>
        <div class="date">
          <%= distance_of_time_in_words(DateTime.now, post.created_at) %> ago 
        </div>
      </div>
      <%= link_to dashboard_path(post.id), class: "comment" do %>
        <% if current_user.image.blank? && !current_user.avatar_image.attached? %>
          <%= image_tag "image.png" %>
        <% elsif current_user.avatar_image.attached?  %>
          <%= image_tag current_user.avatar_image %>
        <% else %>
          <%= image_tag current_user.image %>
        <% end %>
        <div class="add-comment">
          Add a comment...
        </div>
        <div class="post-button">
          Post
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/dashboard/_tutorials_posts.html.erb
<% @posts.reverse.each do |post| %>
  <div class="post">
    <div class="top">
      <div class="left">
        <%= image_tag @creator.avatar_image.attached? ? @creator.avatar_image : "profile.jpg" %>
        <div class="details">
          <div class="name">
            <%= @creator.first_name %> <%= @creator.last_name %>
          </div>
          <div class="username">
            @<%= @creator.username %>
          </div>
        </div>
        <div class="right">
          <div class="date">
          </div>
        </div>
      </div>
    </div>
    <div class="middle">
      <%= link_to dashboard_tutorial_path(post.id) do %>
        <% if post.content_image.content_type.include?("image")%>
          <%= image_tag url_for(post.content_image) %>
        <% else %>
          <%= video_tag url_for(post.content_image), controls: true, height: "500px", width: "500px"%>
        <% end %>
      <% end %>
    </div>
    <div class="bottom">
      <div class="details-wrapper">
        <div class="buttons">
          <div class="left-button">
            <div class="like">
              <div class="like-button">
                <% if post.liked?(current_user) %>
                  <%= link_to post.likes.find_by(user_id: current_user.id), method: :delete do %>
                    <%= image_tag "like.png" %>
                  <% end %>
                <% else %>
                  <%= render 'layouts/like', like: @like, user_id: current_user.id, post_id: post.id %>
                <% end %>
              </div>
              <div class="count-like"></div>
            </div>
            <%= image_tag "comment.png" %>
            <%= image_tag "send.png" %>
          </div>
          <div class="right-button">
            <%= image_tag "save.png" %>
          </div>
        </div>
        <div class="down">
          <% if post.users_liked.blank? %>
          <% else %>
            <div class="liked-by">
              Liked by <span><%= pluralize(post.users_liked.count, "fan") %></span>
            </div>
          <% end %>
        </div>
        <div class="post-details">
          <span><%= post.title %></span> <%= post.description %>
        </div>
        <div class="date">
          <%= distance_of_time_in_words(DateTime.now, post.created_at) %> ago 
        </div>
      </div>
      <%= link_to dashboard_path(post.id), class: "comment" do %>
        <% if current_user.image.blank? && !current_user.avatar_image.attached? %>
          <%= image_tag "image.png" %>
        <% elsif current_user.avatar_image.attached?  %>
          <%= image_tag current_user.avatar_image %>
        <% else %>
          <%= image_tag current_user.image %>
        <% end %>
        <div class="add-comment">
          Add a comment...
        </div>
        <div class="post-button">
          Post
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/dashboard/benefactor.html.erb
<div class="dashboard">
  <header>
    <nav>
      <div class="left">
        <%= image_tag "logo.png", class: "logo" %>
        <ul>
          <li>Feed</li>
          <li><%= link_to "Plans", plans_path %></li>
          <li>Liked Posts</li>
        </ul>
      </div>
      <div class="right">
        <div class="dropdown">
          <button class="dropbtn">
            <% if current_user.image.blank? %>
              <%= image_tag "image.png" %>
            <% else %>
              <%= image_tag current_user.image %>
            <% end %>
          </button>
          <div class="dropdown-content">
            <%= link_to "Settings", edit_user_registration_path %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete%>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main>
    <div class="feed">
      <% @posts.reverse.each do |post| %>
        <div class="post">
          <div class="top">
            <div class="left">
              <%= image_tag @creator.image %>
              <div class="details">
                <div class="name">
                  <%= @creator.first_name %> <%= @creator.last_name %>
                </div>
                <div class="username">
                  @<%= @creator.username %>
                </div>
              </div>
              <div class="right">
                <div class="date">
                </div>
              </div>
            </div>
          </div>
          <div class="middle">
            <%= link_to dashboard_path(post.id) do %>
              <%= image_tag post.content_image %>
            <% end %>
          </div>
          <div class="bottom">
            <div class="details-wrapper">
              <div class="buttons">
                <div class="left-button">
                  <div class="like">
                    <div class="like-button">
                      <% if post.liked?(current_user) %>
                        <%= link_to post.likes.find_by(user_id: current_user.id), method: :delete do %>
                          <%= image_tag "like.png" %>
                        <% end %>
                      <% else %>
                        <%= render 'layouts/like', like: @like, user_id: current_user.id, post_id: post.id %>
                      <% end %>
                    </div>
                    <div class="count-like"></div>
                  </div>
                  <%= image_tag "comment.png" %>
                  <%= image_tag "send.png" %>
                </div>
                <div class="right-button">
                  <%= image_tag "save.png" %>
                </div>
              </div>
              <div class="down">
                <% if post.users_liked.blank? %>
                <% else %>
                  <div class="liked-by">
                    Liked by <span><%= pluralize(post.users_liked.count, "fan") %></span>
                  </div>
                <% end %>
              </div>
              <div class="post-details">
                <span><%= post.title %></span> <%= post.description %>
              </div>
              <div class="date">
                <%= distance_of_time_in_words(DateTime.now, post.created_at) %> ago 
              </div>
            </div>
            <%= link_to dashboard_path(post.id), class: "comment" do %>
              <%= image_tag current_user.image %>
              <%= render "comments/form", comment: Comment.new, post: post%>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </main>
</div>

app/views/dashboard/index.html.erb
<div class="dashboard">
  <header>
    <nav>
      <div class="left">
        <%= image_tag "logo.png", class: "logo" %>
        <ul>
          <li class="focus"><%= link_to "Feed", dashboard_index_path %></li>
          <li><%= link_to "Sketches", dashboard_sketches_path %></li>
          <li><%= link_to "Tutorials", dashboard_tutorials_path %></li>
          <li><%= link_to "Plans", plans_path %></li>
        </ul>
      </div>
      <div class="right">
        <div class="dropdown">
          <button class="dropbtn">
            <% if current_user.image.blank? && !current_user.avatar_image.attached? %>
              <%= image_tag "image.png" %>
            <% elsif current_user.avatar_image.attached?  %>
              <%= image_tag current_user.avatar_image %>
            <% else %>
              <%= image_tag current_user.image %>
            <% end %>
          </button>
          <div class="dropdown-content">
            <%= link_to "Settings", edit_user_registration_path %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete%>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main>
    <div class="feed">
      <% if current_user.supporter? %>
        <%= render "dashboard/posts", scope: @supporter_posts %>
      <% elsif current_user.patron? %>
        <%= render "dashboard/posts", scope: @patron_posts %>
      <% else %>
        <%= render "dashboard/posts", scope: @posts %>
      <% end %>
    </div>
  </main>
</div>
<% if alert.present? %>
<div class="alert">
  <div class="container">
    <div class="message">
      <%= image_tag "alert.png" %>
      <%= alert %>
    </div>
    <%= link_to "Close", dashboard_index_path %>
  </div>
</div>
<% elsif notice.present? %>
<div class="notice">
  <div class="container">
    <div class="message">
      <%= image_tag "notice.png" %>
      <%= notice %>
    </div>
    <%= link_to "Close", dashboard_index_path %>
  </div>
</div>
<% end %>

app/views/dashboard/patron.html.erb
<div class="dashboard">
  <header>
    <nav>
      <div class="left">
        <%= image_tag "logo.png", class: "logo" %>
        <ul>
          <li>Feed</li>
          <li><%= link_to "Plans", plans_path %></li>
          <li>Liked Posts</li>
        </ul>
      </div>
      <div class="right">
        <div class="dropdown">
          <button class="dropbtn">
            <% if current_user.image.blank? %>
              <%= image_tag "image.png" %>
            <% else %>
              <%= image_tag current_user.image %>
            <% end %>
          </button>
          <div class="dropdown-content">
            <%= link_to "Settings", edit_user_registration_path %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete%>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main>
    <div class="feed">
      <% @posts.reverse.each do |post| %>
        <div class="post">
          <div class="top">
            <div class="left">
              <%= image_tag @creator.image %>
              <div class="details">
                <div class="name">
                  <%= @creator.first_name %> <%= @creator.last_name %>
                </div>
                <div class="username">
                  @<%= @creator.username %>
                </div>
              </div>
              <div class="right">
                <div class="date">
                </div>
              </div>
            </div>
          </div>
          <div class="middle">
            <%= link_to dashboard_path(post.id) do %>
              <%= image_tag post.content_image %>
            <% end %>
          </div>
          <div class="bottom">
            <div class="details-wrapper">
              <div class="buttons">
                <div class="left-button">
                  <div class="like">
                    <div class="like-button">
                      <% if post.liked?(current_user) %>
                        <%= link_to post.likes.find_by(user_id: current_user.id), method: :delete do %>
                          <%= image_tag "like.png" %>
                        <% end %>
                      <% else %>
                        <%= render 'layouts/like', like: @like, user_id: current_user.id, post_id: post.id %>
                      <% end %>
                    </div>
                    <div class="count-like"></div>
                  </div>
                  <%= image_tag "comment.png" %>
                  <%= image_tag "send.png" %>
                </div>
                <div class="right-button">
                  <%= image_tag "save.png" %>
                </div>
              </div>
              <div class="down">
                <% if post.users_liked.blank? %>
                <% else %>
                  <div class="liked-by">
                    Liked by <span><%= pluralize(post.users_liked.count, "fan") %></span>
                  </div>
                <% end %>
              </div>
              <div class="post-details">
                <span><%= post.title %></span> <%= post.description %>
              </div>
              <div class="date">
                <%= distance_of_time_in_words(DateTime.now, post.created_at) %> ago 
              </div>
            </div>
            <%= link_to dashboard_path(post.id), class: "comment" do %>
              <%= image_tag current_user.image %>
              <%= render "comments/form", comment: Comment.new, post: post%>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </main>
</div>

app/views/dashboard/show.html.erb
<div class="show-post">
  <div class="overlay">
    <div class="container">
      <div class="nav">
        <%= link_to dashboard_index_path do %>
          <%= image_tag "show-back.png" %>
        <% end %>
        <%= image_tag "logo.png" %>
      </div>
      <main>
        <div class="left">
          <% if @post.content_image.content_type.include?("image") %>
            <%= image_tag url_for(@post.content_image) %>
          <% else %>
            <%= video_tag url_for(@post.content_image), controls: true, height: "550px", width: "550px" %>
          <% end %>
          <div class="details">
            <span class="title">
              <%= @post.title %>
            </span>
            <%= @post.description %>
          </div>
          <div class="date">
            <%= distance_of_time_in_words(DateTime.now, @post.created_at) %> ago 
          </div>
        </div>
        <div class="right">
          <div class="creator">
            <%= image_tag @creator.avatar_image.attached? ? @creator.avatar_image : "profile.jpg" %>
            <div class="info">
              <div class="name">
                <%= @creator.first_name %> <%= @creator.last_name %>
              </div>
              <div class="username">
                @<%= @creator.username %>
              </div>
            </div>
          </div>
          <div class="comments">
            <% if @post.comments.blank? %>
              <div class="blank">No comments</div>
            <% else %>
              <% @post.comments.each do |comment| %>
                <div class="comment">
                  <% if comment.user.image.blank? && !comment.user.avatar_image.attached? %>
                    <%= image_tag "image.png" %>
                  <% elsif comment.user.avatar_image.attached?  %>
                    <%= image_tag comment.user.avatar_image %>
                  <% else %>
                    <%= image_tag comment.user.image %>
                  <% end %>
                  <div class="text">
                    <div class="username">
                      @<%= comment.user.username%>
                      <div class="date">
                        <%= comment.created_at.strftime("%D") %>
                      </div>
                    </div>
                    <div class="message">
                      <%= comment.message %>
                    </div>
                  </div>
                  <% if comment.user == current_user || current_user.admin? %>
                    <%= link_to post_comment_path(@post.id, comment.id), method: :delete, class: "delete-comment-button" do %>
                      <%= image_tag "trash.png", class: "trash" %>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
          <div class="like">
            <div class="like-button">
              <% if @post.liked?(current_user) %>
                <%= link_to @post.likes.find_by(user_id: current_user.id), method: :delete do %>
                  <%= image_tag "like.png" %>
                <% end %>
              <% else %>
                <%= render 'layouts/like', like: @like, user_id: current_user.id, post_id: @post.id %>
              <% end %>
            </div>
            <%= image_tag "comment.png" %>
            <%= image_tag "send.png" %>
          </div>
          <% if @post.users_liked.blank? %>
          <% else %>
            <div class="count-like">Liked by <span><%= pluralize(@post.users_liked.count, "fan") %></span></div>
          <% end %>
          <div class="add-comment">
            <% if current_user.image.blank? && !current_user.avatar_image.attached? %>
              <%= image_tag "image.png" %>
            <% elsif current_user.avatar_image.attached?  %>
              <%= image_tag current_user.avatar_image %>
            <% else %>
              <%= image_tag current_user.image %>
            <% end %>
            <%= render "comments/form", comment: Comment.new, post: @post, autofocus: true %>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>
<% if alert.present? %>
<div class="alert">
  <div class="container">
    <div class="message">
      <%= image_tag "alert.png" %>
      <%= alert %>
    </div>
    <%= link_to "Close", dashboard_path(@post) %>
  </div>
</div>
<% end %>