config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}, path_prefix: "devise"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root "home#index"
  resources :like, only: %i[create destroy]
  resources :users, only: %i[index]
  resources :home, only: %i[index]
  
  namespace :dashboard do
    resources :sketches, only: %i[index show]
    resources :tutorials, only: %i[index show]
  end
  
  resources :dashboard, only: %i[index show]

  resources :posts do
    resources :comments, only: %i[create destroy]
  end

  resources :subscribers, only: %i[index]

  resources :plans, only: %i[index]

  namespace :plans do
    get "patron"
    get "benefactor"
  end

  namespace :payments do
    post "card"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :content_image, attached: true

  has_one_attached :content_image

  has_many :comments, dependent: :destroy
  has_many :users_commented, through: :comments, source: :user

  has_many :likes, dependent: :destroy
  has_many :users_liked, through: :likes, source: :user

  enum scope: {supporter: 0, patron: 1, benefactor: 2}

  def liked?(user)
    !!self.likes.find_by(user_id: user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check_user

  def index
    @posts = Post.all
    @comment = Comment.new
    @creator = User.find_by(role: "admin")
    @total_likes = Like.all.count
    @total_fans = User.where.not(role: "admin").count
    @total_posts = @posts.count
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_url(@post), notice: "Post was successfully created." 
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if @post.update(post_params)
      redirect_to post_url(@post), notice: "Post was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :content_image, :scope)
    end

    def check_user
      redirect_to dashboard_index_path unless current_user.admin?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <% post.errors.each do |error| %>
        <div><%= error.full_message %></div>
      <% end %>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div class="field">
    <%= form.label :content_image %>
    <div class="image">
      <% if post.content_image.attached? %>
        <% if post.content_image.content_type.include?("image")%>
          <%= image_tag url_for(post.content_image) %>
        <% else %>
          <%= video_tag url_for(post.content_image), autoplay: true, height: "50px", width: "100px", muted: true, loop: true%>
        <% end %>
      <% end %>
      <%= form.file_field :content_image %>
    </div>
  </div>
  <div class="field">
    <%= form.label :scope %>
    <%= form.select :scope, options_for_select(["supporter", "patron", "benefactor"]) %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="add-post">
  <div class="container">
    <div class="title"><%= link_to :back do %>
        <%= image_tag "show-back.png" %>
      <% end %>Edit Post</div>
    <%= render 'form', post: @post %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="posts">
  <header>
    <nav>
      <div class="left">
        <%= image_tag "logo.png", class: "logo" %>
        <ul>
          <li class="focus"><%= link_to "Home", dashboard_index_path %></li>
          <li><%= link_to "Fans", users_path %></li>
          <li><%= link_to "Transactions", subscribers_path %></li>
        </ul>
      </div>
      <div class="right">
        <div class="dropdown">
          <button class="dropbtn">
            <% if !current_user.avatar_image.attached? %>
              <%= image_tag "profile.jpg" %>
            <% else %>
              <%= image_tag current_user.avatar_image %>
            <% end %>
          </button>
          <div class="dropdown-content">
            <%= link_to "Settings", edit_user_registration_path %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete%>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main>
    <div class="sticky">
      <div class="banner"></div>
      <div class="creator">
        <% if !current_user.avatar_image.attached? %>
          <%= image_tag "profile.jpg" %>
        <% else %>
          <%= image_tag current_user.avatar_image %>
        <% end %>
        <div class="name">
          <%= @creator.first_name %> <%= @creator.last_name %>
        </div>
        <div class="username">
          @<%= @creator.username %>
        </div>
        <div class="data">
          <div class="post-count count">
            <div class="number"><%= @total_posts %></div>
            <div class="label">Posts</div>
          </div>
          <div class="fan-count count">
            <div class="number"><%= @total_fans %></div>
            <div class="label">Fans</div>
          </div>
          <div class="like-count count">
            <div class="number"><%= @total_likes %></div>
            <div class="label">Likes</div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="feed">
        <div class="title">
          <div class="name">Posts</div>
          <%= link_to "+ New", new_post_path, class: "new-post-button" %>
        </div>
        <% if @posts.blank? %>
          <div class="blank">No posts</div>
        <% else %>
          <div class="posts">
            <% @posts.order(created_at: :desc).each do |post| %>
              <%= link_to post, class: "post" do %>
                <% if post.content_image.content_type.include?("image")%>
                  <%= image_tag url_for(post.content_image) %>
                <% else %>
                  <%= video_tag url_for(post.content_image), controls: true, height: "320px", width: "320px"%>
                <% end %>
                <div class="like-comment">
                  <div class="like">
                    <%= image_tag "unlike.png" %>
                    <%= post.users_liked.count %>
                  </div>
                  <div class="comment">
                    <%= image_tag "comment.png" %>
                    <%= post.comments.count %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </main>
</div>

app/views/posts/new.html.erb
<div class="add-post">
  <div class="container">
    <div class="title"><%= link_to :back do %>
        <%= image_tag "show-back.png" %>
      <% end %>New Post</div>
    <%= render 'form', post: @post %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="show-post">
  <div class="overlay">
    <div class="container">
      <div class="nav">
        <div>
          <%= link_to posts_path do %>
            <%= image_tag "show-back.png" %>
          <% end %>
        </div>
        <div>
          <%= link_to edit_post_path(@post), class: "edit-post-button" do %>
            <%= image_tag "edit-post.png" %>
          <% end %>
          <%= link_to post_path(@post), method: :delete, class: "delete-post-button" do %>
            <%= image_tag "black-trash.png" %>
          <% end %>
        </div>
      </div>
      <main>
        <div class="left">
          <% if @post.content_image.content_type.include?("image") %>
            <%= image_tag url_for(@post.content_image) %>
          <% else %>
            <%= video_tag url_for(@post.content_image), controls: true, height: "550px", width: "550px" %>
          <% end %>
          <div class="details">
            <span class="title">
              <%= @post.title %>
            </span>
            <%= @post.description %>
          </div>
          <div class="date">
            <%= distance_of_time_in_words(DateTime.now, @post.created_at) %> ago 
          </div>
        </div>
        <div class="right">
          <div class="creator">
            <% if !current_user.avatar_image.attached? %>
              <%= image_tag "profile.jpg" %>
            <% else %>
              <%= image_tag current_user.avatar_image %>
            <% end %>
            <div class="info">
              <div class="name">
                <%= current_user.first_name %> <%= current_user.last_name %>
              </div>
              <div class="username">
                @<%= current_user.username %>
              </div>
            </div>
          </div>
          <div class="comments">
            <% if @post.comments.blank? %>
              <div class="blank">No comments</div>
            <% else %>
              <% @post.comments.each do |comment| %>
                <div class="comment">
                  <% if comment.user.image.blank? && !comment.user.avatar_image.attached? %>
                    <%= image_tag "image.png" %>
                  <% elsif comment.user.avatar_image.attached?  %>
                    <%= image_tag comment.user.avatar_image %>
                  <% else %>
                    <%= image_tag comment.user.image %>
                  <% end %>
                  <div class="text">
                    <div class="username">
                      @<%= comment.user.username%>
                      <div class="date">
                        <%= comment.created_at.strftime("%D") %>
                      </div>
                    </div>
                    <div class="message">
                      <%= comment.message %>
                    </div>
                  </div>
                  <% if comment.user == current_user || current_user.admin? %>
                    <%= link_to post_comment_path(@post.id, comment.id), method: :delete, class: "delete-comment-button" do %>
                      <%= image_tag "trash.png", class: "trash" %>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
          <div class="like">
            <%= image_tag "unlike.png" %>
            <%= image_tag "comment.png" %>
            <%= image_tag "send.png" %>
          </div>
          <% if @post.users_liked.blank? %>
          <% else %>
            <div class="count-like">Liked by <span><%= pluralize(@post.users_liked.count, "fan") %></span></div>
          <% end %>
          <div class="add-comment">
            <% if !current_user.avatar_image.attached? %>
              <%= image_tag "profile.jpg" %>
            <% else %>
              <%= image_tag current_user.avatar_image %>
            <% end %>
            <%= render "comments/form", comment: Comment.new, post: @post, autofocus: true %>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>
<% if alert.present? %>
<div class="alert">
  <div class="container">
    <div class="message">
      <%= image_tag "alert.png" %>
      <%= alert %>
    </div>
    <%= link_to "Close", post_path(@post) %>
  </div>
</div>
<% end %>