config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}, path_prefix: "devise"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root "home#index"
  resources :like, only: %i[create destroy]
  resources :users, only: %i[index]
  resources :home, only: %i[index]
  
  namespace :dashboard do
    resources :sketches, only: %i[index show]
    resources :tutorials, only: %i[index show]
  end
  
  resources :dashboard, only: %i[index show]

  resources :posts do
    resources :comments, only: %i[create destroy]
  end

  resources :subscribers, only: %i[index]

  resources :plans, only: %i[index]

  namespace :plans do
    get "patron"
    get "benefactor"
  end

  namespace :payments do
    post "card"
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
    before_action :confirm_role

    def index
    end

    def patron
        @price = 19_900
    end
    
    def benefactor
        @price = 49_900
    end

    def confirm_role
        redirect_to posts_path if current_user.admin?
    end
end

app/views/plans/_form.html.erb
<div class="form-wrap">
  <%= form_with model: PaymentInfo.new, url: payments_card_path, method: :post, class: "payment-form" do |form| %>
    <div class="header">
      <%= link_to plans_path do %>
        <%= image_tag "show-back.png" %>
      <% end %>
      <label class="payment-title">Credit Card Payment</label>
    </div>
    <div class="field">
      <%= form.label :name, "Name on card" %>
      <%= form.text_field :name %>
    </div>
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email, placeholder: "email@example.com" %>
    </div>
    <div class="field">
      <%= form.label :card_number %>
      <%= form.text_field :card_number, placeholder: "●●●● ●●●● ●●●● ●●●●" %>
    </div>
    <div class="card-details">
      <div class="field">
        <%= form.label :exp_month %>
        <%= form.number_field :exp_month %>
      </div>
      <div class="field">
        <%= form.label :exp_year %>
        <%= form.number_field :exp_year %>
      </div>
      <div class="field">
        <%= form.label :cvc, "CVC" %>
        <%= form.text_field :cvc %>
      </div>
    </div>
    <%= form.hidden_field :price, value: @price %>
    <%= form.hidden_field :plan, value: action_name %>
    <div class="actions">
      <%= form.submit "Complete Payment" %>
    </div>
  <% end %>
</div>

app/views/plans/benefactor.html.erb
<%= render "form" %>
<% if alert.present? %>
<div class="alert">
  <div class="container">
    <div class="message">
      <%= image_tag "alert.png" %>
      <%= alert %>
    </div>
    <%= link_to "Close", plans_benefactor_path %>
  </div>
</div>
<% end %>

app/views/plans/index.html.erb
<div class="plans">
  <header>
    <nav>
      <div class="left">
        <%= image_tag "logo.png", class: "logo" %>
        <ul>
          <li><%= link_to "Feed", dashboard_index_path %></li>
          <li><%= link_to "Sketches", dashboard_sketches_path %></li>
          <li><%= link_to "Tutorials", dashboard_tutorials_path %></li>
          <li class="focus"><%= link_to "Plans", plans_path %></li>
        </ul>
      </div>
      <div class="right">
        <div class="dropdown">
          <button class="dropbtn">
           <% if current_user.image.blank? && !current_user.avatar_image.attached? %>
              <%= image_tag "image.png" %>
            <% elsif current_user.avatar_image.attached?  %>
              <%= image_tag current_user.avatar_image %>
            <% else %>
              <%= image_tag current_user.image %>
            <% end %>
          </button>
          <div class="dropdown-content">
            <%= link_to "Settings", edit_user_registration_path %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete%>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main>
    <div class="title">Pricing</div>
    <div class="text">Choose a plan that works best for you.</div>
    <div class="container">
      <div class="box">
        <div class="bottom free">
          <div class="details">
            <div class="plan">Supporter</div>
            <div class="price">Free</div>
            <div class="description">Free plan for all users. </div>
            <div class="check">
              <%= image_tag "plan-check.png" %>
              Access to all finished artworks
            </div>
            <div class="check">
              <%= image_tag "plan-check.png" %>
              Like and comment to creator's posts
            </div>
          </div>
          <% if current_user.benefactor? || current_user.patron? %>
          <% else %>
            <div class="top">
              Current Plan
            </div>
          <% end %>
        </div>
      </div>
      <div class="box">
        <div class="bottom patron">
          <div class="details">
            <div class="plan">Patron</div>
            <div class="price">
              ₱199<span>/month</span>
            </div>
            <div class="description">Ideal for individual artists. </div>
            <div class="check">
              <%= image_tag "plan-check.png" %>
              Access to all sketches
            </div>
            <div class="check">
              <%= image_tag "plan-check.png" %>
              Access to all finished artworks
            </div>
            <div class="check">
              <%= image_tag "plan-check.png" %>
              Like and comment to creator's posts
            </div>
          </div>
          <% if current_user.benefactor? %>
          <% elsif current_user.patron? %>
            <div class="top">
              Current Plan
            </div>
          <% else%>
            <%= link_to "Get Patron Plan", plans_patron_path, class: "button" %>
          <% end %>
        </div>
      </div>
      <div class="box">
        <div class="bottom benefactor">
          <div class="details">
            <div class="plan">Benefactor</div>
            <div class="price">
              ₱499<span>/month</span>
            </div>
            <div class="description">Learn and improve. </div>
            <div class="check">
              <%= image_tag "plan-check.png" %>
              Watch art timelapse
            </div>
            <div class="check">
              <%= image_tag "plan-check.png" %>
              Access to all video tutorials
            </div>
            <div class="check">
              <%= image_tag "plan-check.png" %>
              Access to all sketches
            </div>
            <div class="check">
              <%= image_tag "plan-check.png" %>
              Access to all finished artworks
            </div>
            <div class="check">
              <%= image_tag "plan-check.png" %>
              Like and comment to creator's posts
            </div>
          </div>
          <% if current_user.benefactor? %>
            <div class="top">
              Current Plan
            </div>
          <% else %>
            <%= link_to "Get Benefactor Plan", plans_benefactor_path, class: "button" %>
          <% end %>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/plans/patron.html.erb
<%= render 'form' %>
<% if alert.present? %>
<div class="alert">
  <div class="container">
    <div class="message">
      <%= image_tag "alert.png" %>
      <%= alert %>
    </div>
    <%= link_to "Close", plans_patron_path %>
  </div>
</div>
<% end %>